ddd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -82,7 +82,7 @@ jobs:
 #        run: mvn test -DsuiteXmlFile=testng.xml
 
       - name: Generate Allure Report
-        run: allure generate allure-results -o allure-results || echo "Allure report generation failed"
+        run: allure generate allure-results -o allure-results --clean || echo "Allure report generation failed"
         if: always()
 
       - name: Upload Allure report as artifact   #сохранить отчеты как артефакты в GitHub Actions
